animals_dict = {
    "Grenouille": [0, 0],
    "Chien": [0, 1],
    "Chat": [0, 2],
    "Vache": [0, 3],
    "Lion": [0, 4],
    "Girafe": [0, 5],
    "Singe": [0, 6],
    "Pieuvre": [0, 7],
    "Poisson": [1, 0],
    "Pingouin": [1, 1],
    "Rouge-Gorge": [1, 2],
    "Elephant": [1, 3],
    "Chenille": [1, 4],
    "Requin-Tigre": [1, 5],
    "Corbeau": [1, 6],
    "Ours Polaire": [1, 7],
    "Araignée": [2, 0],
    "Mouche": [2, 1],
    "Chouette": [2, 2],
    "Escargot": [2, 3],
    "Serpent": [2, 4],
    "Rat": [2, 5],
    "Mouton": [2, 6],
    "Crocodile": [2, 7],
}
